tap "azure/functions"
tap "azure/kubelogin"
tap "codecrafters-io/tap"
tap "dapr/tap"
tap "derailed/k9s"
tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "microsoft/git"

brew "azure-cli"
brew "fzf", postinstall: "${HOMEBREW_PREFIX}/opt/fzf/install --all"
brew "neovim"
brew "node"
brew "podman"
brew "ripgrep"
brew "rustup"
brew "tmux"
brew "watch"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "uv"

cask "font-hack-nerd-font"
cask "font-terminus"
cask "git-credential-manager"
cask "google-chrome"
cask "google-cloud-sdk", postinstall: "${HOMEBREW_PREFIX}/bin/gcloud components update"
cask "iterm2"
cask "rectangle"
