tap "azure/bicep"
tap "azure/functions"
tap "azure/functions"
tap "azure/kubelogin"
tap "codecrafters-io/tap"
tap "dapr/tap"
tap "derailed/k9s"
tap "fluxcd/tap"
tap "jesseduffield/lazygit"

brew "azure-cli"
brew "azure-functions-core-tools@4"
brew "bicep"
brew "direnv"
brew "ffmpeg"
brew "fnm"
brew "fzf", postinstall: "${HOMEBREW_PREFIX}/opt/fzf/install --all"
brew "gh"
brew "golang"
brew "gpg"
brew "lazygit"
brew "neovim"
brew "node@22"
brew "pinentry-mac"
brew "podman"
brew "poetry"
brew "postgresql@16"
brew "ripgrep"
brew "rustup"
brew "tmux"
brew "trivy"
brew "uv"
brew "watch"
brew "yq"
brew "zsh-autosuggestions"
brew "zsh-completions"

cask "drawio"
cask "font-cascadia-mono-nf"
cask "font-hack-nerd-font"
cask "git-credential-manager"
cask "github-copilot-for-xcode"
cask "gcloud-cli", postinstall: "${HOMEBREW_PREFIX}/bin/gcloud components update"
cask "iterm2"
cask "rectangle"
