tap "azure/functions"
tap "azure/kubelogin"
tap "codecrafters-io/tap"
tap "dapr/tap"
tap "derailed/k9s"
tap "fluxcd/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "microsoft/git"

brew "fzf"# , postinstall: "${HOMEBREW_PREFIX}/opt/fzf/install --all"
brew "neovim"
brew "node"
brew "podman"
brew "ripgrep"
brew "rustup"
brew "tmux"
brew "watch"
brew "zsh-autosuggestions"
brew "zsh-completions"

cask "font-hack-nerd-font"
cask "font-terminus"
cask "git-credential-manager"
# cask "iterm2"
