-- DAP stack is currently disabled.
-- To re-enable, uncomment both the vim.pack.add() and the setup block below.

-- vim.pack.add({
--   "https://github.com/nvim-neotest/nvim-nio",
--   "https://github.com/mfussenegger/nvim-dap",
--   "https://github.com/rcarriga/nvim-dap-ui",
--   "https://github.com/igorlfs/nvim-dap-view",
--   "https://github.com/theHamsta/nvim-dap-virtual-text",
--   "https://github.com/stevearc/overseer.nvim",
-- })

-- local dap, dapui = require("dap"), require("dapui")
-- dapui.setup()
-- dap.set_log_level("TRACE")
--
-- vim.fn.sign_define("DapBreakpoint", { text = "●", texthl = "", linehl = "", numhl = "" })
-- vim.fn.sign_define("DapStopped",    { text = "▶️", texthl = "", linehl = "", numhl = "" })
--
-- vim.keymap.set("n", "<leader>db", "<cmd>DapViewToggle<CR>", { desc = "[DAP] Toggle debug view" })
-- vim.keymap.set("n", "<F5>",       dap.continue,             { desc = "[DAP] Continue debugging" })
-- vim.keymap.set("n", "<Leader>b",  dap.toggle_breakpoint,    { desc = "[DAP] Toggle breakpoint" })
-- vim.keymap.set("n", "<Right>",    dap.step_over,            { desc = "[DAP] Step over" })
-- vim.keymap.set("n", "<F10>",      dap.step_over,            { desc = "[DAP] Step over" })
-- vim.keymap.set("n", "<Down>",     dap.step_into,            { desc = "[DAP] Step into" })
-- vim.keymap.set("n", "<F11>",      dap.step_into,            { desc = "[DAP] Step into" })
-- vim.keymap.set("n", "<Up>",       dap.step_out,             { desc = "[DAP] Step out" })
-- vim.keymap.set("n", "<F12>",      dap.step_out,             { desc = "[DAP] Step out" })
--
-- dap.listeners.before.attach.dapui_config = function() dapui.open() end
-- dap.listeners.before.launch.dapui_config = function() dapui.open() end
--
-- require("dap.ext.vscode").json_decode = require("json5").parse
-- require("dap.ext.vscode").load_launchjs(nil, {
--   node    = { "typescript", "javascript" },
--   coreclr = { "cs" },
-- })
--
-- local js_debug_adapter = {
--   type = "server", host = "::1", port = "${port}",
--   executable = { command = "js-debug-adapter", args = { "${port}" } },
-- }
-- dap.adapters.node        = js_debug_adapter
-- dap.adapters.javascript  = js_debug_adapter
-- dap.adapters.typescript  = js_debug_adapter
-- dap.adapters["pwa-node"] = js_debug_adapter
--
-- dap.adapters.codelldb   = { type = "executable", command = "codelldb", name = "codelldb" }
-- dap.adapters.debugpy    = { type = "executable", command = "debugpy-adapter" }
-- dap.adapters.netcoredbg = { type = "executable", command = "netcoredbg", args = { "--interpreter=vscode" } }
-- dap.adapters.coreclr    = dap.adapters.netcoredbg
