-- vim.pack.add({
-- 	"https://github.com/kevinhwang91/promise-async",
-- 	"https://github.com/kevinhwang91/nvim-ufo",
-- })
--
-- require("ufo").setup()
-- vim.keymap.set("n", "zR", require("ufo").openAllFolds, { desc = "Open all folds" })
-- vim.keymap.set("n", "zM", require("ufo").closeAllFolds, { desc = "Close all folds" })
