"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = """$directory$git_branch$git_status$git_state$git_metrics$character$fill $all"""
# palette = ""
right_format = """"""

[fill]

[aws]
symbol = " "

[azure]
symbol = " "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[container]
symbol = " "

[deno]
symbol = " "

[direnv]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[gcloud]
symbol = "󱇶 "
disabled = true

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[git_metrics]
disabled = false

[golang]
symbol = " "

[gradle]
symbol = " "
format = "[$symbol($version )]($style)"

[helm]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
disabled = true
symbol = " "
format = "[${symbol}(${version} )]($style)"

[kotlin]
disabled = true
symbol = " "
format = "[$symbol($version )]($style)"

[kubernetes]
symbol = "󱃾 "
disabled = false
style = "#326ce5"
format = '[$symbol $context \($namespace\)]($style) '
# contexts = [
#   { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
# ]
detect_files = []

[lua]
symbol = " "

[maven]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[sudo]
symbol = " "

[terraform]
symbol = " "
