name: CI

on:
  push:
    branches:
    - master

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
    - name: New machine bootstrap
      run: |
        sudo apt update && \
        sudo apt install -y curl git zsh software-properties-common && \
        curl -sL https://raw.githubusercontent.com/damienpontifex/dotfiles/master/.bootstrap | zsh

  macos-build:
    runs-on: macos-latest
    steps:
    - name: New machine bootstrap
      run: curl -sL https://raw.githubusercontent.com/damienpontifex/dotfiles/master/.bootstrap | zsh

